# Generated by Django 3.2 on 2021-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_event_is_how_can_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleenrollfor',
            name='phone_number',
            field=models.CharField(default='NiL', max_length=90),
        ),
    ]
