# Generated by Django 3.2 on 2021-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_peopleenrollfor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleenrollfor',
            name='event_name',
            field=models.CharField(default='...', max_length=500),
        ),
    ]
