# Generated by Django 3.2 on 2021-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_peopleenrollfor_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleenrollfor',
            name='event_name',
        ),
    ]
