# Generated by Django 3.2 on 2021-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211211_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_menu',
            field=models.CharField(default='..', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='..', max_length=300),
        ),
    ]
